### ISSUE TITLE
dt-validate: TypeError: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by xypron** [devicetree-org/dt-schema#49]
I try to validate a device-tree in yaml format.
[a.yaml.txt](https://github.com/devicetree-org/dt-schema/files/5480753/a.yaml.txt)

Unfortunately this results in an error:

```
$ dt-validate /tmp/a.yaml
Traceback (most recent call last):
  File "/usr/local/bin/dt-validate", line 4, in <module>
    __import__('pkg_resources').run_script('dtschema==2020.8.2.dev11+gf66186d', 'dt-validate')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/dtschema-2020.8.2.dev11+gf66186d-py3.8.egg/EGG-INFO/scripts/dt-validate", line 159, in <module>
    sg.check_trees(filename, testtree)
  File "/usr/local/lib/python3.8/dist-packages/dtschema-2020.8.2.dev11+gf66186d-py3.8.egg/EGG-INFO/scripts/dt-validate", line 108, in check_trees
    self.check_subtree(dt, subtree, "/", "/", filename)
  File "/usr/local/lib/python3.8/dist-packages/dtschema-2020.8.2.dev11+gf66186d-py3.8.egg/EGG-INFO/scripts/dt-validate", line 94, in check_subtree
    self.check_node(tree, subtree, nodename, fullname, filename)
  File "/usr/local/lib/python3.8/dist-packages/dtschema-2020.8.2.dev11+gf66186d-py3.8.egg/EGG-INFO/scripts/dt-validate", line 39, in check_node
    node['$nodename'] = [ nodename ]
TypeError: 'str' object does not support item assignment
```

I have been using DTC 1.4.4 to convert the dtb to dts ([a.dts.txt](https://github.com/devicetree-org/dt-schema/files/5480774/a.dts.txt)) and dts2yaml (https://github.com/pantoniou/yamldt) to convert the dts to yaml

**Comment by robherring** [comment]
The yaml encoding supported by dtschema is the yaml output from dtc. That's not the same as dts2yaml.

**Comment by xypron** [comment]
We should mention that the devicetree compiler can be used for dts to yaml transcoding in the README.md. Unfortunately even current Linux distributions (e.g. Debian Bullseye) come with dtc versions before 1.5.0 and therefore this is not evident.

**Comment by xypron** [comment]
There seems to be a bug in dtc. It generates:

    compatible: ["wand,imx6q-wandboard\0fsl,imx6q"]

instead of

    compatible: ["wand,imx6q-wandboard", "fsl,imx6q"]

resulting in a dt-validate warning:

    compatible:0: 'wand,imx6q-wandboard\x00fsl,imx6q' does not match '^[a-zA-Z][a-zA-Z0-9,+\\-._]+$'

**Comment by robherring** [comment]
Are you doing dtb->yaml or dtb->dts->yaml as that wouldn't work. Only dts->yaml works as there is some type information in dts files that you lose in a dtb.

**Comment by robherring** [comment]
It appears to be fine here: https://gitlab.com/robherring/linux-dt-bindings/-/jobs/826489577
