### ISSUE TITLE
tools/dt-doc-validate seems to fail

### ISSUE THREAD

**Issue by sjg20** [devicetree-org/dt-schema#86]
with commit:

99646e2 (HEAD, us/master, us/main) meta-schemas: Restrict 'const' to scalar values

Perhaps I am doing it wrong but I thought this use to work:

# tools/dt-doc-validate dtschema
Traceback (most recent call last):
  File "/scratch/sglass/cosarm/dt-schema/tools/dt-doc-validate", line 65, in <module>
    ret = check_doc(filename)
  File "/scratch/sglass/cosarm/dt-schema/tools/dt-doc-validate", line 39, in check_doc
    dtschema.DTValidator.check_schema_refs(filename, testtree)
  File "/scratch/sglass/cosarm/dt-schema/dtschema/lib.py", line 1260, in check_schema_refs
    self._check_schema_refs(schema)
  File "/scratch/sglass/cosarm/dt-schema/dtschema/lib.py", line 1248, in _check_schema_refs
    self._check_schema_refs(v)
  File "/scratch/sglass/cosarm/dt-schema/dtschema/lib.py", line 1248, in _check_schema_refs
    self._check_schema_refs(v)
  File "/scratch/sglass/cosarm/dt-schema/dtschema/lib.py", line 1248, in _check_schema_refs
    self._check_schema_refs(v)
  File "/scratch/sglass/cosarm/dt-schema/dtschema/lib.py", line 1245, in _check_schema_refs
    self.resolver.resolve(schema['$ref'])
  File "/home/sglass/.local/lib/python3.10/site-packages/jsonschema/validators.py", line 881, in resolve
    url = self._urljoin_cache(self.resolution_scope, ref).rstrip("/")
  File "/usr/lib/python3.10/urllib/parse.py", line 532, in urljoin
    base, url, _coerce_result = _coerce_args(base, url)
  File "/usr/lib/python3.10/urllib/parse.py", line 125, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments

**Comment by robherring** [comment]
You mean: dt-doc-validate dtschema/schemas/

**Comment by sjg20** [comment]
Thanks
